---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes


- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: "install dependencies."
  become: yes
  apt:
    name: ["apache2"]
    state: latest
    update_cache: yes


- name: Copy index test page
  copy:
    src: index.html
    dest: /var/www/html/index.html
    backup: true

